version: 2
updates:
  # Rubyのgemのアップデート設定
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    groups:
      dependencies:
        patterns:
          - "*" 
